spring:
  datasource:
    url: jdbc:mysql://mysql:3306/catfood?useSSL=false&serverTimezone=Asia/Taipei&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_ROOT_PASSWORD:admin123}

  jpa:
    show-sql: false
